# https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/spec/index.html#structs
[build]
#rustflags = [ "-C", "debuginfo=2", "--emit=llvm-ir" ]

[alias]
# llvm-arg list: https://llvm.org/docs/CommandGuide/llc.html
# release asm
#asm = ["rustc", "--", "--emit", "asm","-C", "llvm-args=-x86-asm-syntax=intel"]

